# Generated by Django 5.2.13 on 2026-04-28 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("current_location", models.CharField(max_length=255)),
                ("current_lat", models.FloatField()),
                ("current_lng", models.FloatField()),
                ("pickup_location", models.CharField(max_length=255)),
                ("pickup_lat", models.FloatField()),
                ("pickup_lng", models.FloatField()),
                ("dropoff_location", models.CharField(max_length=255)),
                ("dropoff_lat", models.FloatField()),
                ("dropoff_lng", models.FloatField()),
                ("cycle_used_hrs", models.FloatField()),
                (
                    "home_timezone",
                    models.CharField(default="America/Chicago", max_length=64),
                ),
                ("total_distance_mi", models.FloatField()),
                ("total_duration_hr", models.FloatField()),
                ("route_geometry", models.JSONField()),
                ("requires_34h_restart", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("from_label", models.CharField(max_length=255)),
                ("to_label", models.CharField(max_length=255)),
                ("total_miles", models.FloatField()),
                ("total_off_duty", models.FloatField()),
                ("total_sleeper", models.FloatField()),
                ("total_driving", models.FloatField()),
                ("total_on_duty", models.FloatField()),
                ("segments", models.JSONField()),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "date"), name="uniq_trip_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TripEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "duty_status",
                    models.CharField(
                        choices=[
                            ("OFF", "Off Duty"),
                            ("SB", "Sleeper Berth"),
                            ("D", "Driving"),
                            ("ON", "On Duty Not Driving"),
                        ],
                        max_length=3,
                    ),
                ),
                ("activity", models.CharField(max_length=64)),
                ("location_label", models.CharField(max_length=255)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(
                        fields=["trip", "sequence"],
                        name="trips_tripe_trip_id_9ed64e_idx",
                    )
                ],
            },
        ),
    ]
